sudo:false

language: cpp
compiler: g++

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_script:
- cd test
- export CXX="g++-4.8"

script: 
- "bash -c ./build.sh"
- ./test
